import type { CuratedReportPayload } from './curate';

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN_X = 50;
const START_Y = 800;
const LINE_HEIGHT = 14;
const MAX_LINES = 50;
const WRAP_AT = 90;

function toAscii(value: string): string {
  return value
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .replace(/[^\x20-\x7E\n]/g, ''); // strip non-ASCII (e.g. Hebrew) rather than replacing with '?'
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function wrapLine(line: string): string[] {
  if (line.length <= WRAP_AT) return [line];

  const words = line.split(' ');
  const wrapped: string[] = [];
  let current = '';

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length <= WRAP_AT) {
      current = next;
    } else {
      if (current) wrapped.push(current);
      current = word;
    }
  }

  if (current) wrapped.push(current);
  return wrapped;
}

function toLines(raw: string[]): string[] {
  const lines: string[] = [];

  for (const line of raw) {
    const normalized = toAscii(line.trim());
    if (!normalized) {
      lines.push('');
      continue;
    }
    lines.push(...wrapLine(normalized));
  }

  if (lines.length > MAX_LINES) {
    return [...lines.slice(0, MAX_LINES - 1), '...'];
  }
  return lines;
}

function buildContentStream(lines: string[]): string {
  let stream = `BT\n/F1 11 Tf\n1 0 0 1 ${MARGIN_X} ${START_Y} Tm\n`;

  lines.forEach((line, index) => {
    if (index > 0) {
      stream += `0 -${LINE_HEIGHT} Td\n`;
    }
    stream += `(${escapePdfText(line)}) Tj\n`;
  });

  stream += 'ET';
  return stream;
}

function buildPdf(contentStream: string): Buffer {
  const streamLength = Buffer.byteLength(contentStream, 'latin1');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`,
    `<< /Length ${streamLength} >>\nstream\n${contentStream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [0];

  objects.forEach((obj, idx) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${idx + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';

  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'latin1');
}

export function toReportPdfFilename(eventName: string): string {
  const base = toAscii(eventName)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64) || 'event';

  return `eventa-report-${base}.pdf`;
}

export function generateReportPdf(params: {
  eventName: string;
  eventId: string;
  payload: CuratedReportPayload;
  aiSummary?: string | null;
  portalUrl?: string;
}): Buffer {
  const { eventName, eventId, payload, aiSummary, portalUrl } = params;
  const { engagement, network, funnel, safety, generated_at: generatedAt } = payload;

  const lines = toLines([
    'Eventa Post-Event Report',
    `Event ID: ${eventId}`,
    `Event Name (see portal): ${toAscii(eventName) || '(Hebrew — see online report)'}`,
    `Generated: ${generatedAt}`,
    '',
    'Key Metrics',
    `Participants: ${network.total_participants}`,
    `Total likes: ${engagement.total_likes}`,
    `Mutual likes: ${engagement.mutual_likes}`,
    `Match rate: ${engagement.match_rate.toFixed(1)}%`,
    `Conversations: ${engagement.total_conversations}`,
    `Messages: ${engagement.total_messages}`,
    '',
    'Funnel',
    ...(funnel.steps ?? []).slice(0, 8).map((step) => `${step.step}: ${step.count}`),
    ...(funnel.top_drop_off ? [`Top drop-off: ${funnel.top_drop_off}`] : []),
    '',
    'Safety',
    `Blocks: ${safety.total_blocks}`,
    `Reports: ${safety.total_reports}`,
    `Banned participants: ${safety.banned_participants}`,
    '',
    ...(aiSummary ? ['AI Summary: see online report (Hebrew content not supported in PDF)'] : []),
    ...(portalUrl ? [`Full report (with Hebrew): ${portalUrl}`] : []),
    '',
    'Generated by Eventa reporting pipeline.',
  ]);

  return buildPdf(buildContentStream(lines));
}
